http:
  routers:
    local-radarr:
      rule: "Host(`radarr.local.starklab.mkroshana.com`) || Host(`movies.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: radarr-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare

  services:
    radarr-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.117:7878"
        passHostHeader: true
