http:
  routers:
    local-prowlarr:
      rule: "Host(`prowlarr.local.starklab.mkroshana.com`) || Host(`indexer.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: prowlarr-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare

  services:
    prowlarr-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.114:9696"
        passHostHeader: true
