http:
  routers:
    local-duplicati:
      rule: "Host(`duplicati.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: duplicati-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare

  services:
    duplicati-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:8200"
        passHostHeader: false
