http:
  routers:
    local-sonarr:
      rule: "Host(`sonarr.local.starklab.mkroshana.com`) || Host(`tvshows.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: sonarr-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare

  services:
    sonarr-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.118:8989"
        passHostHeader: true
