http:
  routers:
    local-plex:
      rule: "Host(`plex.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: plex-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare
