http:
  routers:
    local-qbittorrent:
      rule: "Host(`qbittorrent.local.starklab.mkroshana.com`) || Host(`downloads.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: qbittorrent-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare

  services:
    qbittorrent-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:8090"
        passHostHeader: true
