http:
  routers:
    local-homeassistant:
      rule: "Host(`ha.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: homeassistant-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare
