http:
  routers:
    local-prowlarr:
      rule: "Host(`prowlarr.local.starklab.mkroshana.com`) || Host(`indexer.local.starklab.mkroshana.com`)"
      entryPoints:
        - websecure
      service: prowlarr-svc
      middlewares:
        - local-only
      tls:
        certResolver: cloudflare
